-- MySQL Script generated by MySQL Workbench
-- Thứ hai, 29 Tháng 10 Năm 2018 12:52:36 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Perfume
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Perfume
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Perfume` ;
USE `Perfume` ;

-- -----------------------------------------------------
-- Table `Perfume`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfume`.`Admin` (
  `ID_Admin` INT NOT NULL AUTO_INCREMENT,
  `Full_Name` NVARCHAR(200) NULL,
  `Password` VARCHAR(100) NULL,
  `Role` NVARCHAR(20) NULL,
  PRIMARY KEY (`ID_Admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Perfume`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfume`.`Order` (
  `ID_Order` INT NOT NULL AUTO_INCREMENT,
  `ID_Perfumes` INT NULL,
  `Data` NVARCHAR(200) NULL,
  `Quantity` INT NULL,
  `Total_Money` DECIMAL NULL,
  `ID_Users` INT NULL,
  PRIMARY KEY (`ID_Order`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Perfume`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfume`.`Transaction` (
  `ID_Transaction` INT NOT NULL AUTO_INCREMENT,
  `Status` NVARCHAR(20) NULL,
  `ID_Users` INT NULL,
  `Full_Name` NVARCHAR(200) NULL,
  `Email` VARCHAR(200) NULL,
  PRIMARY KEY (`ID_Transaction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Perfume`.`Type_of_perfume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfume`.`Type_of_perfume` (
  `ID_Type_of_perfume` INT NOT NULL AUTO_INCREMENT,
  `Name_of_perfume` NVARCHAR(200) NULL,
  `ID_Genre` INT NULL,
  PRIMARY KEY (`ID_Type_of_perfume`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Perfume`.`Perfume`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfume`.`Perfume` (
  `ID_Perfume` INT NOT NULL AUTO_INCREMENT,
  `ID_Category` INT NULL,
  `ID_Type_of_perfume` INT NULL,
  `Perfume_Name` NVARCHAR(200) NULL,
  `Price` DECIMAL NULL,
  `Summary` NVARCHAR(150) NULL,
  `Content` LONGTEXT NULL,
  `Discounts` VARCHAR(20) NULL,
  `Image_Link` VARCHAR(100) NULL,
  `Views` INT NULL,
  PRIMARY KEY (`ID_Perfume`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Perfume`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfume`.`Category` (
  `ID_Category` INT NOT NULL AUTO_INCREMENT,
  `Category_name` NVARCHAR(200) NULL,
  PRIMARY KEY (`ID_Category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Perfume`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfume`.`Users` (
  `ID_Users` INT NOT NULL AUTO_INCREMENT,
  `Full_Name` NVARCHAR(200) NULL,
  `Email` VARCHAR(100) NULL,
  `Phone_number` INT NULL,
  `Address` NVARCHAR(200) NULL,
  `Password` VARCHAR(100) NULL,
  `Date_of_registration` DATE NULL,
  PRIMARY KEY (`ID_Users`))
ENGINE = InnoDB;

USE `Perfume` ;

-- -----------------------------------------------------
-- Placeholder table for view `Perfume`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Perfume`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `Perfume`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `Perfume`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Perfume`.`view1`;
USE `Perfume`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
